### ISSUE TITLE
(JS) Referenced Block ID Missing During CHILD Relations Iteration

### ISSUE THREAD

**Issue by serhii12** [aws-samples/amazon-textract-response-parser#187]
I’m encountering this error:

Error: (While iterating CHILD relations of parent 5474eef4-d819-4c07-8483-7d40ce9dd0bb) Referenced block ID 1e229d04-eb11-437e-8a8b-2a583440eb97 not found!

I can’t figure out why this is happening.

Here’s the relevant code snippet:
```
protected processResponse(response: GetDocumentTextDetectionResponse): { pages: any[] } {
    const document = new TextractDocument(response as unknown as ApiDetectDocumentTextResponse);
    return {
        pages: [...document.iterPages()].map(page => ({
            some object here
        })),
    };
}
    at Object.next (/usr/src/app/node_modules/amazon-textract-response-parser/dist/cjs/base.js:212:35)
    at new LayoutGeneric (/usr/src/app/node_modules/amazon-textract-response-parser/dist/cjs/layout.js:376:20)
    at new Page (/usr/src/app/node_modules/amazon-textract-response-parser/dist/cjs/document.js:73:24)
    at TextractDocument._parse (/usr/src/app/node_modules/amazon-textract-response-parser/dist/cjs/document.js:656:30)
    at new TextractDocument (/usr/src/app/node_modules/amazon-textract-response-parser/dist/cjs/document.js:633:14)

```

Additionally, I have a question: is it better to pass the response as an array containing all pages, or should I handle them one by one? I’m working with multi-page documents.

**Comment by athewsey** [comment]
Hi & thanks for reaching out,

The most likely cause for this is probably if you're passing just *part* of a Textract Response, which comes to the second part of your question: Yes, you'll want to pass in an array of all the "pages" of the API response (which may not correspond exactly to "pages" of the document).

The error is thrown because one of the blocks in the API response you're passing in references another block ID that isn't in that data. I think someone else has asked similar before though, so maybe we could try to add some clarification to the docs and/or error message...

Please try passing all your response parts in a single list, and let us know if that resolves it?

**Comment by serhii12** [comment]
Hi,

Thank you for the quick response! Passing all the response parts in a single list resolved the issue, and everything now works smoothly. I appreciate the clarification—this makes a lot more sense. Adding clarification to the docs or error message would definitely help others as well.

Thanks again!
