### ISSUE TITLE
NodeJS import/require errors

### ISSUE THREAD

**Issue by mattmcgiv** [aws-samples/amazon-textract-response-parser#39]
I ran into an error while requiring the NodeJS version following an npm install.

NodeJS: v14.17.6

To reproduce:
```
npm init -y
npm install amazon-textract-response-parser # as per instructions in this package's top-level readme
touch index.js
echo 'const { TextractDocument, TextractExpense } = require("textract-response-parser");' >> index.js
node index.js
```

Output:
```
Error: Cannot find module 'textract-response-parser'
Require stack:
- /{...}/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> ({...}/index.js:1:47)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/{...}/index.js' ]
}
```

**Comment by linuxatico** [comment]
Hi, shouldn't this issue be closed since it's been merged?
