### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by CGarces** [aws-samples/amazon-textract-response-parser#83]
I'm trying to load into trp.Document a .json file that is the result of an texttract execution done with start_document_analysis

The code is done on Python 3.9

I'm loading the json_file in a variable and trying to parse it with trp 
```
    # Load json
    with open(f"/tmp/{file_name}", "rb") as json_file:
        textract_json = json.load(json_file)

   doc = Document(textract_json)
```

It works fine with synchronous calls but not with asynchronous calls

```
Traceback (most recent call last):
  File "/var/task/app.py", line 115, in lambda_handler
    process_file(file_name)
  File "/var/task/app.py", line 53, in process_file
    doc = Document(textract_json)
  File "/var/lang/lib/python3.9/site-packages/trp/__init__.py", line 638, in __init__
    self._parse()
  File "/var/lang/lib/python3.9/site-packages/trp/__init__.py", line 675, in _parse
    page = Page(documentPage["Blocks"], self._blockMap)
  File "/var/lang/lib/python3.9/site-packages/trp/__init__.py", line 522, in __init__
    self._parse(blockMap)
  File "/var/lang/lib/python3.9/site-packages/trp/__init__.py", line 543, in _parse
    t = Table(item, blockMap)
  File "/var/lang/lib/python3.9/site-packages/trp/__init__.py", line 438, in __init__
    cell = Cell(blockMap[cid], blockMap)
  File "/var/lang/lib/python3.9/site-packages/trp/__init__.py", line 361, in __init__
    self._text = self._text + w.text + ' '
```
Using doc = TDocumentSchema().load(textract_json) also give me validation exceptions.

Any clue about what I'm doing wrong?

**Comment by schadem** [comment]
Can you share the result JSON @CGarces ?

**Comment by anjanvb** [comment]
@schadem this happens when an individual JSON from the Async job is passed directly to `Document` without going through the `get_full_json_from_output_config` route to combine all of them together. I think technically it should be possible to pass in a single JSON to `Document` without having to combine it. Thoughts?

**Comment by anjanvb** [comment]
I was able to aggregate multiple JSONs by page for a 6 page document so JSON `1` only contain Page 1 related data. I still encountered issue in [this line](https://github.com/aws-samples/amazon-textract-response-parser/blob/70820a416949a01a4e8c9e2a66d6869a4c021579/src-python/trp/__init__.py#L361).

**Comment by schadem** [comment]
We should do a streaming implementation of the 'full' paginated JSON files to generate the individual page-JSON's. That way we save on memory consumption, which is pretty huge for a 3000 page document actually.

**Comment by LutzFassl** [comment]
Hello! I stumbled across this discussion because I got this error when processing a response that was generated from ASYNC API of a TIFF file (e.g. 1-page document if you will). I ran the remove_none function with success as as workaround.

But what is the preferred way to use the amazon-textract-response-parser with ASYNC 1-page results to avoid this error?

**Comment by schadem** [comment]
Can you share your JSON file @LutzFassl ?

**Comment by LutzFassl** [comment]
Yes, no problem:
[response.zip](https://github.com/aws-samples/amazon-textract-response-parser/files/11541323/response.zip)

Library version is: 0.1.46
Python 3.10.8

**Error:**
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[15], line 26
     22 response = json.loads(response)
     25 # Parse with amazon-textract-response-parser
---> 26 doc = Document(response)
     29 # Post-process
     30 parse_response(doc)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/trp/__init__.py:638, in Document.__init__(self, responsePages)
    635 self._responsePages = responsePages
    636 self._pages = []
--> 638 self._parse()

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/trp/__init__.py:675, in Document._parse(self)
    673 self._responseDocumentPages, self._blockMap = self._parseDocumentPagesAndBlockMap()
    674 for documentPage in self._responseDocumentPages:
--> 675     page = Page(documentPage["Blocks"], self._blockMap)
    676     self._pages.append(page)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/trp/__init__.py:522, in Page.__init__(self, blocks, blockMap)
    519 self._content = []
    520 self._custom = dict()
--> 522 self._parse(blockMap)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/trp/__init__.py:543, in Page._parse(self, blockMap)
    541     self._text = self._text + l.text + '\n'
    542 elif item["BlockType"] == "TABLE":
--> 543     t = Table(item, blockMap)
    544     self._tables.append(t)
    545     self._content.append(t)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/trp/__init__.py:438, in Table.__init__(self, block, blockMap)
    436 cells: List[Cell] = list()
    437 for cid in rs['Ids']:


--> 438     cell = Cell(blockMap[cid], blockMap)
    439     cells.append(cell)
    440 cells.sort(key=lambda cell: (cell.rowIndex, cell.columnIndex))

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/trp/__init__.py:361, in Cell.__init__(self, block, blockMap)
    359     w = Word(blockMap[cid], blockMap)
    360     self._content.append(w)
--> 361     self._text = self._text + w.text + ' '
    362 elif (blockType == "SELECTION_ELEMENT"):
    363     se = SelectionElement(blockMap[cid], blockMap)

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
`

**Comment by schadem** [comment]
I see a lot of "null" values in the response, which I can not reproduce, even when using a TIFF file against the async API. All the responses I get exclude the null. But I added a fix for the Text and will close this one once merged.

```
        "BlockType": "CELL",
        "ColumnIndex": 1,
        "ColumnSpan": 1,
        "Confidence": 89.208984375,
        "EntityTypes": null,
        "Geometry": {
            "BoundingBox": {
                "Height": 0.03404336795210838,
                "Left": 0.0030097656417638063,
                "Top": 0.9265893697738647,
                "Width": 0.1632784903049469
            },
            "Polygon": [{
                "X": 0.0030097656417638063,
                "Y": 0.9265893697738647
            }, {
                "X": 0.16500058770179749,
                "Y": 0.9298586249351501
            }, {
                "X": 0.16628825664520264,
                "Y": 0.9606327414512634
            }, {
                "X": 0.004291444085538387,
                "Y": 0.957396388053894
            }]
        },
        "Hint": null,
        "Id": "938bb8d3-bc8f-4678-9254-a7cf244b48c0",
        "Page": 1,
        "PageClassification": null,
        "Query": null,
        "Relationships": [{
            "Ids": ["e9a25c51-e258-4ce6-be79-768a6a6cf0d4", "e7fa05cd-092a-46a8-bb9c-f77ccec231fb"],
            "Type": "CHILD"
        }],
        "RowIndex": 1,
        "RowSpan": 1,
        "SelectionStatus": null,
        "Text": null,
        "TextType": null
```
